[package]
name    = "{{demo}}"
version = "0.1.0"
authors = [ "SÃ©bastien Crozet <developer@crozet.re>" ]
edition = "2018"

[dependencies]
rand       = { version = "0.6", features = [ "stdweb" ] }
num-traits = "0.2"
nalgebra   = "0.18"
ncollide3d = "0.20"
kiss3d     = "0.21"

[profile.release]
lto = true
codegen-units = 1

[dependencies.nphysics3d]
path = "{{nphysics3d_dir}}"

[dependencies.nphysics_testbed3d]
path = "{{testbed3d_dir}}"


[[bin]]
name = "{{demo}}"
path = "./{{demo}}.rs"


[patch.crates-io]
ncollide3d = { path = "../rust-dev/ncollide-dev/build/ncollide3d" }
